// <auto-generated />
using System;
using HomeBnB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeBnB.Migrations
{
    [DbContext(typeof(HomeBnBContext))]
    [Migration("20190903160517_LandLord")]
    partial class LandLord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeBnB.Models.Apartment", b =>
                {
                    b.Property<int>("ApartmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<int?>("LandLordID");

                    b.Property<int>("NumberOfRooms");

                    b.Property<string>("Owner");

                    b.Property<double>("Price");

                    b.Property<bool>("Renovated");

                    b.HasKey("ApartmentID");

                    b.HasIndex("LandLordID");

                    b.ToTable("Apartment");
                });

            modelBuilder.Entity("HomeBnB.Models.LandLord", b =>
                {
                    b.Property<int>("LandLordID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.HasKey("LandLordID");

                    b.ToTable("LandLord");
                });

            modelBuilder.Entity("HomeBnB.Models.Apartment", b =>
                {
                    b.HasOne("HomeBnB.Models.LandLord")
                        .WithMany("Apartments")
                        .HasForeignKey("LandLordID");
                });
#pragma warning restore 612, 618
        }
    }
}
